"""initial

Revision ID: ffb470c04210
Revises:
Create Date: 2026-09-19 19:40:26.606076
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ffb470c04210'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('dim_dates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(length=50), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('weekday_number', sa.Integer(), nullable=False),
    sa.Column('weekday_name', sa.String(length=50), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_date')
    )
    op.create_table('dim_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('accepted_rows', sa.Integer(), nullable=False),
    sa.Column('rejected_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('fact_production',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('produced_quantity', sa.Integer(), nullable=False),
    sa.Column('sold_quantity', sa.Integer(), nullable=False),
    sa.Column('discarded_quantity', sa.Integer(), nullable=False),
    sa.Column('discard_reason', sa.String(length=255), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['date_id'], ['dim_dates.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['dim_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prod_batch', 'fact_production', ['import_batch_id'], unique=False)
    op.create_index('ix_prod_date', 'fact_production', ['date_id'], unique=False)
    op.create_index('ix_prod_product', 'fact_production', ['product_id'], unique=False)
    op.create_table('fact_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_order_id', sa.String(length=100), nullable=False),
    sa.Column('external_item_id', sa.String(length=200), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=True),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['dim_channels.id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['dim_dates.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['dim_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_order_id', 'external_item_id', name='uq_sale_item')
    )
    op.create_index('ix_sale_batch', 'fact_sales', ['import_batch_id'], unique=False)
    op.create_index('ix_sale_channel', 'fact_sales', ['channel_id'], unique=False)
    op.create_index('ix_sale_date', 'fact_sales', ['date_id'], unique=False)
    op.create_index('ix_sale_product', 'fact_sales', ['product_id'], unique=False)
    op.create_index('ix_sale_status', 'fact_sales', ['status'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_errors')
    op.drop_index('ix_sale_status', table_name='fact_sales')
    op.drop_index('ix_sale_product', table_name='fact_sales')
    op.drop_index('ix_sale_date', table_name='fact_sales')
    op.drop_index('ix_sale_channel', table_name='fact_sales')
    op.drop_index('ix_sale_batch', table_name='fact_sales')
    op.drop_table('fact_sales')
    op.drop_index('ix_prod_product', table_name='fact_production')
    op.drop_index('ix_prod_date', table_name='fact_production')
    op.drop_index('ix_prod_batch', table_name='fact_production')
    op.drop_table('fact_production')
    op.drop_table('import_batches')
    op.drop_table('dim_products')
    op.drop_table('dim_dates')
    op.drop_table('dim_channels')
    # ### end Alembic commands ###
